# Generated by Django 2.2.24 on 2022-07-03 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0035_auto_20220412_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsizelimit',
            name='max_size',
            field=models.BigIntegerField(default=5368709120, help_text='The maximum file size allowed for upload (bytes).', validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
